### ISSUE TITLE
GPX loading

### ISSUE THREAD

**Issue by zaari** [zaari/garta#11]
Implement support for loading GPX files.

**Comment by brendanashworth** [comment]
@zaari hi! I'm not sure if you're particularly acquainted with the [georust project](https://github.com/georust), but I've been working on [rust-gpx](https://github.com/georust/rust-gpx) that may do what you're looking for here — if not, we can always add what you're looking for as well. Let me know if that helps!

**Comment by zaari** [comment]
@brendanashworth The last time I check georust out it didn't support non-Euclidean geometry and thus is a no-go for Garta. I have to check out whether rust-gpx can be used as a standalone dependency or not.

**Comment by brendanashworth** [comment]
@zaari interesting — I'm actually not too familiar with the main georust library, I just do rust-gpx. In actuality rust-gpx interacts minimally with the main library and should be able to be used on its own, with a small wrapper.

In rust-gpx, each [`Waypoint`](https://docs.rs/gpx/0.1.0/gpx/struct.Waypoint.html) has a [`.point()`](https://docs.rs/gpx/0.1.0/gpx/struct.Waypoint.html#method.point) that gives a [`geo::Point`](https://docs.rs/geo/0.6.3/geo/struct.Point.html) type. If you wanted to make it work with your library you could wrap it to add [`.into() -> Location`](https://github.com/zaari/garta/blob/2533e787831729bbc090f1b74b35672535b71c39/src/geocoord/geo.rs#L249) for a `geo::Point`, and then continue to use your own geo tools.

Also, I see you use a `LinkedList` for waypoints and tracks, etc. Rust-gpx uses vectors right now, but I've been toying with the idea of using LLs.

**Comment by zaari** [comment]
@brendanashworth Garta's GPX-related data structures are from the very early phase of the project and definitely need some re-thinking and refactoring. If I make the app depend on rust-gpx crate then it's better to dump the old code completely and go on with rust-gpx practices. Use of `LinkedList` isn't anything final. As Rust's documentation says, almost always it is better to use `Vec` or `VecDeque` instead of `LinkedList` as array-based containers are more efficient. The `.into` like conversion from `geo::Point` to `Location` sounds like a good idea but the implementation has to be made as efficient as possible.
